EscolaMVC/Models/CursoViewModels.cs
namespace EscolaMVC.Models
{
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    public class CursoViewModels
    {
        [DisplayName("Curso")]
        [Key]
        public int CursoId { get; set; }

        [DisplayName("Nome do Curso")]
        [Required(ErrorMessage = "Preencha o Nome do Curso")]
        [StringLength(100, MinimumLength = 3, ErrorMessage = "O nome do curso deve ter entre 3 a 100 caracteres")]
        public string NomeCurso { get; set; }

        public ICollection<TurmaViewModels> Turmas { get; set; }


    }
}

EscolaMVC/Controllers/CursoController.cs
namespace EscolaMVC.Controllers
{
    using EscolaMVC.Models;
    using System.Data.Entity;
    using System.Linq;
    using System.Net;
    using System.Web.Mvc;
    [Authorize(Roles = "Administrador")]
    public class CursoController : Controller
    {
        private MyContext db = new MyContext();

        // GET: Curso
        public ActionResult Index()
        {
            return View(db.Curso.ToList());
        }

        // GET: Curso/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CursoViewModels cursoViewModels = db.Curso.Find(id);
            if (cursoViewModels == null)
            {
                return HttpNotFound();
            }
            return View(cursoViewModels);
        }

        // GET: Curso/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Curso/Create
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "CursoId,NomeCurso")] CursoViewModels cursoViewModels)
        {
            if (ModelState.IsValid)
            {
                db.Curso.Add(cursoViewModels);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(cursoViewModels);
        }

        // GET: Curso/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CursoViewModels cursoViewModels = db.Curso.Find(id);
            if (cursoViewModels == null)
            {
                return HttpNotFound();
            }
            return View(cursoViewModels);
        }

        // POST: Curso/Edit/5
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "CursoId,NomeCurso")] CursoViewModels cursoViewModels)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cursoViewModels).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(cursoViewModels);
        }

        // GET: Curso/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CursoViewModels cursoViewModels = db.Curso.Find(id);
            if (cursoViewModels == null)
            {
                return HttpNotFound();
            }
            return View(cursoViewModels);
        }

        // POST: Curso/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            CursoViewModels cursoViewModels = db.Curso.Find(id);
            db.Curso.Remove(cursoViewModels);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EscolaMVC/Controllers/TurmaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace EscolaMVC.Models
{
    [Authorize(Roles = "Administrador")]
    public class TurmaController : Controller
    {
        private MyContext db = new MyContext();
        [Authorize]
        // GET: Turma
        public ActionResult Index(int? id)
        {
           if(id == null)
            {
                var turma = db.Turma.Include(t => t.Curso);
                return View(turma.ToList());
            }
            else
            {
                var Turma = from x in db.Turma.Include(t => t.Curso)
                            where x.CursoId == id
                            select x;


                return View(Turma.ToList());
            }

        }

       
        // GET: Turma/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TurmaViewModels turmaViewModels = db.Turma.Find(id);
            var turmas = db.Turma.Include(t => t.Curso).ToList();

             var Turma = from x in db.Turma.Include(t => t.Curso)
                     where x.TurmaId == id
                     select x;

            if (turmaViewModels == null)
            {
                return HttpNotFound();
            }
            return View(Turma.FirstOrDefault());
        }

        // GET: Turma/Create
        public ActionResult Create()
        {
            ViewBag.CursoId = new SelectList(db.Curso, "CursoId", "NomeCurso");
            return View();
        }

        // POST: Turma/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TurmaId,NomeTurma,CursoId")] TurmaViewModels turmaViewModels)
        {
            if (ModelState.IsValid)
            {
                db.Turma.Add(turmaViewModels);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CursoId = new SelectList(db.Curso, "CursoId", "NomeCurso", turmaViewModels.CursoId);
            return View(turmaViewModels);
        }

        // GET: Turma/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TurmaViewModels turmaViewModels = db.Turma.Find(id);
            if (turmaViewModels == null)
            {
                return HttpNotFound();
            }
            ViewBag.CursoId = new SelectList(db.Curso, "CursoId", "NomeCurso", turmaViewModels.CursoId);
            return View(turmaViewModels);
        }

        // POST: Turma/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TurmaId,NomeTurma,CursoId")] TurmaViewModels turmaViewModels)
        {
            if (ModelState.IsValid)
            {
                db.Entry(turmaViewModels).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CursoId = new SelectList(db.Curso, "CursoId", "NomeCurso", turmaViewModels.CursoId);
            return View(turmaViewModels);
        }

        // GET: Turma/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TurmaViewModels turmaViewModels = db.Turma.Find(id);
            var turmas = db.Turma.Include(t => t.Curso).ToList();

            var Turma = from x in db.Turma.Include(t => t.Curso)
                        where x.TurmaId == id
                        select x;

            if (turmaViewModels == null)
            {
                return HttpNotFound();
            }
            return View(Turma.FirstOrDefault());
        }

        // POST: Turma/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TurmaViewModels turmaViewModels = db.Turma.Find(id);
            db.Turma.Remove(turmaViewModels);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

EscolaMVC/Views/Curso/Create.cshtml
@model EscolaMVC.Models.CursoViewModels

@{
    ViewBag.Title = "Criar Curso";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Criar Curso</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.NomeCurso, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NomeCurso, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NomeCurso, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Criar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar para a Lista", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EscolaMVC/Views/Curso/Delete.cshtml
@model EscolaMVC.Models.CursoViewModels

@{
    ViewBag.Title = "Apagar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Apagar</h2>

<h3>Tem a certeza que deseja apagar?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NomeCurso)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NomeCurso)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Apagar" class="btn btn-default" /> |
            @Html.ActionLink("Voltar para a lista", "Index")
        </div>
    }
</div>

EscolaMVC/Views/Curso/Details.cshtml
@model EscolaMVC.Models.CursoViewModels

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Detalhes</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NomeCurso)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NomeCurso)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.CursoId }) |
    @Html.ActionLink("Voltar para a lista", "Index")
</p>

EscolaMVC/Views/Curso/Edit.cshtml
@model EscolaMVC.Models.CursoViewModels

@{
    ViewBag.Title = "Editar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Editar</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CursoId)

        <div class="form-group">
            @Html.LabelFor(model => model.NomeCurso, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NomeCurso, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NomeCurso, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar para a lista", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EscolaMVC/Views/Curso/Index.cshtml
@model IEnumerable<EscolaMVC.Models.CursoViewModels>

@{
    ViewBag.Title = "Lista de Cursos";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Lista de Cursos</h2>

<p>
    @Html.ActionLink("Criar Curso", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.NomeCurso)
           
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.NomeCurso)
        </td>
        <td>
            @Html.ActionLink("Editar", "Edit", new { id = item.CursoId }) |
            @Html.ActionLink("Apagar", "Delete", new { id = item.CursoId })  |
            @Html.ActionLink("Atribuir Disciplinas", "Create", "CursoDisciplina", routeValues: new { id = item.CursoId }, htmlAttributes: null) |
            @Html.ActionLink("Ver Turmas", "Index", "Turma", routeValues: new { id = item.CursoId }, htmlAttributes: null)
        </td>
    </tr>
}

</table>